### PR TITLE
Feat: Automate backups

### PR DESCRIPTION
**Pull request by PedroChaparro**
## Description

1. Bash script to create the backup, compress the folder and upload to gdrive. 
2. Workflow to execute the bash script automatically. 

## Notes 

The target branch is main on purpose.

### CODE REVIEW

**Comment by Woynert** [comment]
A few things I want to point out:
- The script doesn't clean after the process is done, leaving behind the uncompressed backup directory.
- The time stamp printed in every step is recycled so it's inaccurate.
- It may be useful to add the hour and minute to the backup name in case we need to run it again the same day.

**Review by Woynert — CHANGES_REQUESTED** [review]
A few things I want to point out:

- The script doesn't clean after the process is done, leaving behind the uncompressed backup directory.
- The time stamp printed in every step is recycled so it's inaccurate.
- It may be useful to add the hour and minute to the backup name in case we need to run it again the same day.

**Comment by PedroChaparro** [comment]
¿Are you ok with removing the uncompressed directory but keep the .tar.gz? @Woynert

**Comment by Woynert** [comment]
@PedroChaparro That's fine if what we want is to keep a local copy. Although I'm not too comfortable storing it in the same machine which runs the business logic.

**Review by Woynert — APPROVED** [review]

**Review by SilviaPabon — APPROVED** [review]

**Pull request merged**
